spring.application.name=nutrition-app

spring.datasource.url=jdbc:postgresql://localhost:5432/dbNutrition
spring.datasource.username=devuser
spring.datasource.password=1212

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true