spring.application.name=nutrition-app

spring.datasource.url=jdbc:postgresql://localhost:5432/dbNutrition
spring.datasource.username=devuser
spring.datasource.password=1212

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SMTP settings for email verification (configure for your mail provider)
 spring.mail.host=smtp.gmail.com
 spring.mail.port=587
 spring.mail.username=meturk26@gmail.com
 spring.mail.password=odps tbkp kjfb nieo
 spring.mail.properties.mail.smtp.auth=true
 spring.mail.properties.mail.smtp.starttls.enable=true